### ISSUE TITLE
Error during rosmake tum_ardrone

### ISSUE THREAD

**Issue by rabenimmermehr** [tum-vision/tum_ardrone#5]
Servus,

I'm new to ROS and am currently trying to set up this package.

I downloaded and installed ROS according to the tutorials, created a ros-workspace (not catkin) and followed your instructions.

But during the "rosmake tum_ardrone" i always get the following error:

make[3]: Betrete Verzeichnis '/home/fabi/ros_ws/tum_ardrone/thirdparty/libcvd/build'
g++ -O3 -I. -I.  -INONE/include -g  -Wall -Wextra -pipe -ggdb -fPIC -mmmx -msse -msse -msse2 -msse3 -pthread -c progs/video_play_source.cc -o progs/vi$
progs/video_play_source.cc: In Funktion »void play(std::string)«:
progs/video_play_source.cc:200:17: Fehler: es gibt keine Argumente für »usleep«, die von einem Templateparameter abhängen, weshalb eine Deklaration vo$
progs/video_play_source.cc:200:17: Anmerkung: (mit »-fpermissive« wird G++ den Code akzeptieren, aber die Verwendung eines nicht deklarierten Namens i$
progs/video_play_source.cc: In Instanziierung von »void play(std::string) [with C = CVD::Rgb<unsigned char>; std::string = std::basic_string<char>]«:
progs/video_play_source.cc:241:30:   von hier erfordert
progs/video_play_source.cc:200:4: Fehler: »usleep« wurde in diesem Gültigkeitsbereich nicht definiert
In file included from ./cvd/internal/convert_pixel_types.h:27:0,
                 from ./cvd/image_convert.h:25,
                 from ./cvd/colourspacebuffer.h:27,
                 from ./cvd/videosource.h:13,
                 from progs/video_play_source.cc:38:
./cvd/internal/scalar_convert.h: Im globalen Gültigkeitsbereich:
./cvd/internal/scalar_convert.h:112:21: Warnung: »CVD::Pixel::Internal::init_float_for_byte« definiert, aber nicht verwendet [-Wunused-variable]
./cvd/internal/scalar_convert.h:113:21: Warnung: »CVD::Pixel::Internal::init_double_for_byte« definiert, aber nicht verwendet [-Wunused-variable]
make[3]: **\* [progs/video_play_source.o] Fehler 1
make[3]: Verlasse Verzeichnis '/home/fabi/ros_ws/tum_ardrone/thirdparty/libcvd/build'
make[2]: **\* [libcvd_built] Fehler 2
make[2]: Verlasse Verzeichnis '/home/fabi/ros_ws/tum_ardrone/thirdparty/libcvd'
make[1]: **\* [all] Fehler 2
make[1]: Verlasse Verzeichnis '/home/fabi/ros_ws/tum_ardrone/thirdparty'
make: **\* [all] Fehler 2

FFMPEG is installed, do I need anything else?

Kind regards,
Fabi

**Comment by rabenimmermehr** [comment]
Alrighty, following this tutorial  http://gcc.gnu.org/gcc-4.7/porting_to.html I included <unistd.h>. where necessary...
Then I had to include cv_bridge which I did and now I am stuck with the following error:

/home/fabi/ros_ws/tum_ardrone/thirdparty/TooN/include/TooN/internal/allocator.hh:58:3: Fehler: »debug_initialize« wurde in diesem Gültigkeitsbereich nicht deklariert, und bei argumentabhängiger Suche am Ort der Instanziierung wurden keine Deklarationen gefunden [-fpermissive]
  In file included from /home/fabi/ros_ws/tum_ardrone/thirdparty/TooN/include/TooN/TooN.h:255:0,
                   from /home/fabi/ros_ws/tum_ardrone/src/stateestimation/GLWindow2.h:12,
                   from /home/fabi/ros_ws/tum_ardrone/src/stateestimation/PTAMWrapper.h:24,
                   from /home/fabi/ros_ws/tum_ardrone/src/stateestimation/PTAMWrapper.cpp:23:
  /home/fabi/ros_ws/tum_ardrone/thirdparty/TooN/include/TooN/internal/debug.hh:100:33: Anmerkung: »template<class P> void TooN::Internal::debug_initialize(P_, int)« hier deklariert, später in Übersetzungseinheit
  In file included from /home/fabi/ros_ws/tum_ardrone/thirdparty/TooN/include/TooN/TooN.h:250:0,
                   from /home/fabi/ros_ws/tum_ardrone/src/stateestimation/GLWindow2.h:12,
                   from /home/fabi/ros_ws/tum_ardrone/src/stateestimation/PTAMWrapper.h:24,
                   from /home/fabi/ros_ws/tum_ardrone/src/stateestimation/PTAMWrapper.cpp:23:
  /home/fabi/ros_ws/tum_ardrone/thirdparty/TooN/include/TooN/internal/allocator.hh: In Instanziierung von »TooN::Internal::StackOrHeap<Size, Precision, false>::StackOrHeap() [with int Size = 3; Precision = int]«:
  /home/fabi/ros_ws/tum_ardrone/thirdparty/TooN/include/TooN/internal/allocator.hh:105:43:   erfordert durch »TooN::Internal::VectorAlloc<Size, Precision>::VectorAlloc() [with int Size = 3; Precision = int]«
  /home/fabi/ros_ws/tum_ardrone/thirdparty/TooN/include/TooN/internal/vbase.hh:96:16:   erfordert durch »TooN::Internal::GenericVBase<Size, Precision, Stride, Mem>::GenericVBase() [with int Size = 3; Precision = int; int Stride = 1; Mem = TooN::Internal::VectorAlloc<3, int>]«
  /home/fabi/ros_ws/tum_ardrone/thirdparty/TooN/include/TooN/internal/vbase.hh:72:12:   erfordert durch »TooN::Internal::VBase::VLayout<Size, Precision>::VLayout() [with int Size = 3; Precision = int]«
  /home/fabi/ros_ws/tum_ardrone/thirdparty/TooN/include/TooN/internal/vector.hh:143:17:   erfordert durch »TooN::Vector<Size, Precision, Base>::Vector() [with int Size = 3; Precision = int; Base = TooN::Internal::VBase]«
  /home/fabi/ros_ws/tum_ardrone/thirdparty/TooN/include/TooN/internal/make_vector.hh:34:24:   erfordert durch »TooN::Vector<3, Precision> TooN::makeVector(const Precision&, const Precision&, const Precision&) [with Precision = int]«
  /home/fabi/ros_ws/tum_ardrone/src/stateestimation/PTAMWrapper.cpp:667:48:   von hier erfordert
  /home/fabi/ros_ws/tum_ardrone/thirdparty/TooN/include/TooN/internal/allocator.hh:58:3: Fehler: »debug_initialize« wurde in diesem Gültigkeitsbereich nicht deklariert, und bei argumentabhängiger Suche am Ort der Instanziierung wurden keine Deklarationen gefunden [-fpermissive]
  In file included from /home/fabi/ros_ws/tum_ardrone/thirdparty/TooN/include/TooN/TooN.h:255:0,
                   from /home/fabi/ros_ws/tum_ardrone/src/stateestimation/GLWindow2.h:12,
                   from /home/fabi/ros_ws/tum_ardrone/src/stateestimation/PTAMWrapper.h:24,
                   from /home/fabi/ros_ws/tum_ardrone/src/stateestimation/PTAMWrapper.cpp:23:
  /home/fabi/ros_ws/tum_ardrone/thirdparty/TooN/include/TooN/internal/debug.hh:100:33: Anmerkung: »template<class P> void TooN::Internal::debug_initialize(P_, int)« hier deklariert, später in Übersetzungseinheit
  In file included from /home/fabi/ros_ws/tum_ardrone/thirdparty/libcvd/include/cvd/internal/convert_pixel_types.h:27:0,
                   from /home/fabi/ros_ws/tum_ardrone/thirdparty/libcvd/include/cvd/utility.h:11,
                   from /home/fabi/ros_ws/tum_ardrone/src/stateestimation/PTAM/MiniPatch.h:16,
                   from /home/fabi/ros_ws/tum_ardrone/src/stateestimation/PTAM/Tracker.h:26,
                   from /home/fabi/ros_ws/tum_ardrone/src/stateestimation/PTAMWrapper.cpp:28:
  /home/fabi/ros_ws/tum_ardrone/thirdparty/libcvd/include/cvd/internal/scalar_convert.h: Im globalen Gültigkeitsbereich:
  /home/fabi/ros_ws/tum_ardrone/thirdparty/libcvd/include/cvd/internal/scalar_convert.h:112:21: Warnung: »CVD::Pixel::Internal::init_float_for_byte« definiert, aber nicht verwendet [-Wunused-variable]
  /home/fabi/ros_ws/tum_ardrone/thirdparty/libcvd/include/cvd/internal/scalar_convert.h:113:21: Warnung: »CVD::Pixel::Internal::init_double_for_byte« definiert, aber nicht verwendet [-Wunused-variable]
  make[4]: **\* [CMakeFiles/drone_stateestimation.dir/src/stateestimation/PTAMWrapper.cpp.o] Fehler 1
  make[4]: Verlasse Verzeichnis '/home/fabi/ros_ws/tum_ardrone/build'
  make[3]: **\* [CMakeFiles/drone_stateestimation.dir/all] Fehler 2
  make[3]: Verlasse Verzeichnis '/home/fabi/ros_ws/tum_ardrone/build'
  make[2]: **\* [all] Fehler 2
  make[2]: Verlasse Verzeichnis '/home/fabi/ros_ws/tum_ardrone/build'
  make[1]: **\* [all] Fehler 2
  make[1]: Verlasse Verzeichnis '/home/fabi/ros_ws/tum_ardrone'

**Comment by rabenimmermehr** [comment]
The solution to those errors: I needed to downgrade gcc to version 4.6. Just follow this guide replacing all the version-numbers with the correct ones: http://stackoverflow.com/questions/7832892/how-to-change-the-default-gcc-compiler-in-ubuntu

**Comment by Hendrik-Unger** [comment]
Did you manage to build the Package with gcc 4.6?
I am currently trying to do the build with gcc 4.7.2:
The solution to your last error is to uprgrade TooN to the current Version.   But there is another error after that ;)

**Comment by rabenimmermehr** [comment]
It didn't build right away. You had to change the g++ references somewhere too and then I got another error (some missing libraries) which can be resolved following this guide:
http://faculty.washington.edu/rjl/uwamath583s11/sphinx/notes/html/lapack_install.html

Yeah, I tried that, but it was just an endless stream of errors. That's why I tried to compile it on the virtual image provided by ROS, where it didn't throw any major errors. Problem is, that the virtual machine is too slow.
The only difference to my Ubuntu image was the version of gcc, so I downgraded it.

**Comment by Hendrik-Unger** [comment]
Oh that was a good advice.  Did the downgrade and it took quite a long time before an error was thrown :)  
I installed the library that is mentioned in your Link (http://faculty.washington.edu/rjl/uwamath583s11/sphinx/notes/html/lapack_install.html)
via sudo apt-get install liblapack-dev    --> if I understand correctly for Ubuntu that should be enough.

but still get these Errors: 

g++ -o progs/calibrate progs/calibrate.o -L. -lcvd -ltiff -ljpeg -lpng -lpng -llapack -lGLU -lGL -lrt -L -lX11 -lXext -pthread
./libcvd.so: undefined reference to `XMoveWindow'
./libcvd.so: undefined reference to`XCreateGlyphCursor'
./libcvd.so: undefined reference to `XStoreName'
./libcvd.so: undefined reference to`XLookupString'
./libcvd.so: undefined reference to `XFreeFont'
./libcvd.so: undefined reference to`XSetClassHint'
./libcvd.so: undefined reference to `XCreateWindow'
./libcvd.so: undefined reference to`XCreateColormap'
./libcvd.so: undefined reference to `XOpenDisplay'
./libcvd.so: undefined reference to`XDestroyWindow'
./libcvd.so: undefined reference to `XCloseDisplay'
./libcvd.so: undefined reference to`XUnmapWindow'
./libcvd.so: undefined reference to `XNextEvent'
./libcvd.so: undefined reference to`XSetWMProtocols'
./libcvd.so: undefined reference to `XResizeWindow'
./libcvd.so: undefined reference to`XMapWindow'
./libcvd.so: undefined reference to `XSelectInput'
./libcvd.so: undefined reference to`XFlush'
./libcvd.so: undefined reference to `XWarpPointer'
./libcvd.so: undefined reference to`XLoadQueryFont'
./libcvd.so: undefined reference to `XDefineCursor'
./libcvd.so: undefined reference to`XInternAtom'
./libcvd.so: undefined reference to `XQueryPointer'
./libcvd.so: undefined reference to`XUndefineCursor'
./libcvd.so: undefined reference to `XGetWindowAttributes'
./libcvd.so: undefined reference to`XPending'

That looks more like there is something wrong with X11, doesn't it?   Unfortunately my hobby programming skills together with linux are quite poor.

I am running on a VM to, hope it will be fast enough since it is quite a pain to boot Linux from an external drive on a Mac.
What configuration has the system you used?

**Comment by rabenimmermehr** [comment]
I'm not too experienced in Ubuntu either, sorry.

I was running it on a Windows with some i5 Setup, don't know which generation. It is important that you activate 3D-Acceleration, otherwise you will get segmentation faults.

**Comment by Hendrik-Unger** [comment]
Thanks for your help anyway. I took me a big step further.

Hm. So my Laptop seems to be to slow.  I will test it if I manage to run it :)

**Comment by rabenimmermehr** [comment]
Step by step guide:
You download & install ardrone_autonomy as instructed in the tutorial.
Afterwards you do the following:

sudo apt-get install gcc-4.6
sudo apt-get install g++-4.6
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 50
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.6 50
echo 'export CXX=/usr/bin/g++-4.6'  >> ~/.bashrc
echo 'export CC=/usr/bin/gcc-4.6' >> ~/.bashrc

Then you can continue downloading and compiling the tum_ardrone package

**Comment by 23pointsNorth** [comment]
Hello. Did the last suggestion work(downgrading gcc)? 
Up until now I was using gcc-4.7.2. Managed to clear a bit of the errors (like the missing header for usleep)
But came across this:
tum_ardrone/src/stateestimation/GLWindow2.cc:106:17: error: cannot convert ‘CVD::ImageRef’ to ‘GLdouble {aka double}’ for argument ‘1’ to ‘void glOrtho(GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble)’

Any suggestions?

**Comment by Hendrik-Unger** [comment]
Hi,
downgrading GCC solved a lot of the problems I encountered. There was also a bug in libCVD, I had a conversation with Edward Rosten about it. I dont know if the libCVD package is already upgraded here, so you maybe want to do it yourself. Just get it from git and copy it to the correct folder.

Doing all this was as far as I remember enough to get a good build.
Good luck

**Comment by lppier** [comment]
I'm also having an issue with this. 
Stuck at this... can anyone help? Using Ubuntu 12.04, ROS Hydro

It reports just 1 build error which is similar to Hendrik's ... :(

{-------------------------------------------------------------------------------
  Generating config... configuration unchanged
  configure: creating ./config.status
  config.status: creating Makefile
  cd build && export CPATH=../../TooN/include && make
  make[3]: Entering directory `/opt/ros/hydro/tum_ardrone/thirdparty/libcvd/build'
  /usr/bin/g++-4.6 -o progs/cvd_display_image progs/cvd_display_image.o -L. -lcvd  -ltiff -ljpeg -lpng -lpng -lGLU -lGL -lrt  -L -lX11 -lXext -pthread
  ./libcvd.so: undefined reference to`XMoveWindow'
  ./libcvd.so: undefined reference to `XCreateGlyphCursor'
  ./libcvd.so: undefined reference to`XStoreName'
  ./libcvd.so: undefined reference to `XLookupString'
  ./libcvd.so: undefined reference to`XFreeFont'
  ./libcvd.so: undefined reference to `XSetClassHint'
  ./libcvd.so: undefined reference to`XCreateWindow'
  ./libcvd.so: undefined reference to `XCreateColormap'
  ./libcvd.so: undefined reference to`XOpenDisplay'
  ./libcvd.so: undefined reference to `XDestroyWindow'
  ./libcvd.so: undefined reference to`XCloseDisplay'
  ./libcvd.so: undefined reference to `XUnmapWindow'
  ./libcvd.so: undefined reference to`XNextEvent'
  ./libcvd.so: undefined reference to `XSetWMProtocols'
  ./libcvd.so: undefined reference to`XResizeWindow'
  ./libcvd.so: undefined reference to `XMapWindow'
  ./libcvd.so: undefined reference to`XSelectInput'
  ./libcvd.so: undefined reference to `XFlush'
  ./libcvd.so: undefined reference to`XWarpPointer'
  ./libcvd.so: undefined reference to `XLoadQueryFont'
  ./libcvd.so: undefined reference to`XDefineCursor'
  ./libcvd.so: undefined reference to `XInternAtom'
  ./libcvd.so: undefined reference to`XQueryPointer'
  ./libcvd.so: undefined reference to `XUndefineCursor'
  ./libcvd.so: undefined reference to`XGetWindowAttributes'
  ./libcvd.so: undefined reference to `XPending'
  collect2: ld returned 1 exit status
  make[3]: *** [progs/cvd_display_image] Error 1
  make[3]: Leaving directory`/opt/ros/hydro/tum_ardrone/thirdparty/libcvd/build'
  make[2]: **\* [libcvd_built] Error 2
  make[2]: Leaving directory `/opt/ros/hydro/tum_ardrone/thirdparty/libcvd'
  make[1]: *** [all] Error 2
  make[1]: Leaving directory`/opt/ros/hydro/tum_ardrone/thirdparty'

**Comment by Hendrik-Unger** [comment]
Did you already upgrade libCVD?  After I did it those errors disappeared.

**Comment by lppier** [comment]
Hi Hendrik

Thanks I managed to compile it. Were u able to get navdata from the ardrone?

Pier.

**Comment by Hendrik-Unger** [comment]
How exactly do you mean that?     The program showed everything it was
supposed to show.
I did not try to fetch any packages ROS might publicate with data from the
drone.

2014-01-28 lppier notifications@github.com

> Hi Hendrik
> 
> Thanks I managed to compile it. Were u able to get navdata from the
> ardrone?
> 
> Pier.

**Comment by lppier** [comment]
In my drone gui top right under Node Communication Status, the NavData is
0Hz.
I'm not able to get any video in my case.
The PTAM Drone Map View shows up though, but not the video. :/

Pier.

**Comment by lppier** [comment]
Hi Hendrik,

I'm still trying to get this to work...
Can I check with you :
1) Are you using Ubuntu 12.04 on it's own partition? I'm using Ubuntu in
Parallels (mac os) , not sure if that is the problem.
2) What ROS version are you using? I'm using Hydro.

Thank you very much.

Pier.

**Comment by Hendrik-Unger** [comment]
Oh sorry I forgot to answer you.

I used Ubuntu 12.04 on an own Partition and ROS Groovy. Since the AR Drone Package was developed on Fuerte, this might cause problems too.

I think your Video not showing problem is caused by the virtualization. I remember reading something about this issue, but I am not quite sure. Additionally the algorithms in the package use a lot calculation power.  Did you read the papers where PTAM is described?  The used something like a dual core 2.66 Ghz machine.  
My 2011 macbook air really struggled to run this.  It worked, but the map updates have been quite slow.

Installing Ubuntu on a Mac is not the biggest problem, there are good guides for every model on askubunutu.com. Together with Refit it is also easy to choose what to boot.

**Comment by lppier** [comment]
Hi Hendrik,

Do you get this error in when running ardrone_autonomy ardrone_driver ?

_Tag 34866 is an unknown navdata option tag_
_One option (0) is not a valid option because its size is zero_
*[Navdata] Checksum failed : 989 (distant) / 35945 (local) *

Under the drone_stateestimation instance I always get this :

*Waiting for first navdata to determine drone version! *

Any idea what could it be? Who is supposed to send navdata?
Really appreciate your help.
I installed Hydro, now wondering whether to reinstall ROS using Fuerte /
Groovy .

Thanks.

Pier.

Pier.

**Comment by Hendrik-Unger** [comment]
I dropped the drone project some time ago, so I can not check, because I have no drone at hand.
But as far as I remember I have never seen this error.

I think the AR Drone Autonomy Package is supposed to send navdata to the tum package.  

I'd rather use a native install of Linux instead of a VM.  I struggled with this too, because my hard drive size is very limited, but it was worth the effort because the program started working :)

**Comment by lppier** [comment]
Hi Hendrik,

It's ok, thanks. I'm grateful for your help.
Let me try installing Fuerte instead of Hydro, maybe that will help.

Pier.

**Comment by lppier** [comment]
Oh I did try a native install , seems smoother.

Pier.

**Comment by lesire** [comment]
We have a hydro-devel branch now which is compliant with the official ardrone driver from AutonomyLab.
Could you test it and report any issue or close this issue if everything goes well?

**Comment by rohanbhargava11** [comment]
We also want to pull in the latest libcvd library. I had similar problems and installed libcvd from https://github.com/edrosten/libcvd. This solved most of the problems discussed here.

**Comment by lesire** [comment]
the libcvd is now on an archive with other external libs; update the archive and submit a pull request so that I can test it both on groovy and hydro

**Comment by lesire** [comment]
fixed by #19
